theme: minima
title: alexoah Github Pages 
author: alexoah
#email: sendaljepit@rehatsejenak.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! Thank you for your visit.
  
  I haven't got any idea on what to publish here. 
  So, at this moment, I'll just share this quote here:
  
  If you would take, you must first give, this is the beginning of intelligence. 
  ~ Lao Tzu
  (source: https://www.brainyquote.com/quotes/lao_tzu_384788)

# social links
twitter_username: alexoah
github_username:  alexoah

show_excerpts: true # set to false to remove excerpts on the homepage
