theme: jekyll-theme-merlot
title: alexoah Github Pages 
author: alexoah
#email: sendaljepit@rehatsejenak.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! Thank you for your visit.
  
  I haven't got any idea on what to publish here. I'll add more updates later. See ya!
# social links
twitter_username: alexoah
github_username:  alexoah

show_excerpts: true # set to false to remove excerpts on the homepage
